add morph support
digital-entropy/laravel.accounting pull request #1
Opened 2020-11-01 11:36 UTC by rendyananta

This pull requests consists of

1. Morphable support
   1. Every entry must have an author
   1. Every journal can have a recordable

2. Refactoring
3. Add missing code documentations

2020-11-02 15:36 UTC, addeeandra requested changes
LGTM! -- Please see some of my reviews

2020-11-02 15:36 UTC, addeeandra commented on database/migrations/2020_10_30_000002_create_journals_table.php
> +            $table->string('recordable_type')->nullable();
Any reason not to use `nullableMorph('recordable')`?

2020-11-02 15:36 UTC, addeeandra commented on src/Contracts/EntryAuthor.php
> +    function createEntry(Journal $journal, $entry);
The `$entry` argument should strictly defined as `Entry` interface

2020-11-02 15:36 UTC, addeeandra commented on src/Concerns/HasEntries.php
> +    function createEntry(Journal $journal, $entry)
This `$entry` argument should strictly defined as `Entry` interface

2020-11-02 15:39 UTC, addeeandra reviewed
LGTM!

2020-11-03 02:20 UTC, rendyananta commented
Well, I have been implementing your request of changes.

2020-11-05 02:06 UTC, addeeandra approved these changes

2020-11-05 02:07 UTC, merged